CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'ialgac'@'%' IDENTIFIED BY 'force99';
GRANT ALL PRIVILEGES ON wordpress.* TO 'ialgac'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootforce99';